FROM maven:3.8.1-adoptopenjdk-11 AS build
WORKDIR /app
COPY src ./src
COPY pom.xml .
RUN mvn package

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/recentlyviewed-service-1.0.jar recentlyviewedservice.jar
ENTRYPOINT ["java","-jar","/recentlyviewedservice.jar"]
